[editor]
scroll-padding = 5
line-number = "relative"
buffer-line = true
gutters = ["spacer", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "block"
normal = "bar"

[editor.status-bar]
left = ["mode"]
center = ["file-name"]
right = [
  "cursor-percentage",
  "cursor-position",
  "line-count",
  "file-encoding",
  "file-type",
]
mode.normal = "NOR"
mode.insert = "INS"
